// https://icon-sets.iconify.design/material-symbols/

export enum IconName {
  bold = 'material-symbols:format-bold-rounded',
  italic = 'material-symbols:format-italic-rounded',
  underline = 'material-symbols:format-underlined-rounded',
  strikethrough = 'material-symbols:strikethrough-s-rounded',
  alignLeft = 'material-symbols:format-align-left-rounded',
  alignCenter = 'material-symbols:format-align-center-rounded',
  alignRight = 'material-symbols:format-align-right-rounded',
  alignJustify = 'material-symbols:format-align-justify-rounded',
  link = 'material-symbols:link-rounded',
  indent = 'material-symbols:format-indent-decrease-rounded',
  outdent = 'material-symbols:format-indent-increase-rounded',
  tint = 'material-symbols:format-color-text-rounded',
  highlight = 'material-symbols:format-ink-highlighter-rounded',
  undo = 'material-symbols:undo-rounded',
  redo = 'material-symbols:redo-rounded',
  print = 'material-symbols:print-rounded',
  history = 'material-symbols:history-rounded',
  arrowRight = 'material-symbols:arrow-forward-rounded',
  arrowLeft = 'material-symbols:arrow-back-rounded',
  h2 = 'material-symbols:format-h2-rounded',
  h3 = 'material-symbols:format-h3-rounded',
  horizontalRule = 'material-symbols:horizontal-rule-rounded',
  image = 'material-symbols:imagesmode-outline-rounded',
  listOl = 'material-symbols:format-list-numbered-rounded',
  listUl = 'material-symbols:format-list-bulleted-rounded',
  settings = 'material-symbols:settings',
  hexagon = 'material-symbols:hexagon-rounded',
  add = 'material-symbols:add-rounded',
  check = 'material-symbols:check-rounded',
  close = 'material-symbols:close-rounded',
  delete = 'material-symbols:delete-rounded',
  download = 'material-symbols:download-rounded',
  menu = 'material-symbols:menu-rounded',
  search = 'material-symbols:search-rounded',
  character = 'material-symbols:person-rounded',
  location = 'material-symbols:location-on-rounded',
  item = 'material-symbols:diamond-rounded',
  event = 'material-symbols:calendar-today-rounded',
  group = 'material-symbols:interests-rounded',
  note = 'material-symbols:sticky-note-2-rounded',
  book = 'material-symbols:book-2-rounded',
  bookmark = 'material-symbols:bookmark-rounded',
  bookmarks = 'material-symbols:bookmarks-rounded',
  notebook = 'material-symbols:school-rounded',
  details = 'material-symbols:view-list-rounded',
  contents = 'material-symbols:list-alt-rounded',
  hive = 'material-symbols:hive-rounded',
}

export default function useIcon() {
  return {
    IconName,
  }
}
